//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeOrganizer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Article
    {
        public int ArticleID { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string Season { get; set; }
        public string Ocassion { get; set; }
        public string Photo { get; set; }
        [Display(Name = "Clean?")]
        public bool IsClean { get; set; }
        public int ClothingID { get; set; }
    
        public virtual Clothing Clothing { get; set; }
    }
}
